import { GoatDB } from "@goatdb/goatdb";
import { Server, staticAssetsFromJS } from "@goatdb/goatdb/server";
import * as path from "@std/path";

import { registerSchemas } from "@smith/common";
import type { BuildInfo } from "@goatdb/goatdb";

registerSchemas();

import type { JSONObject } from "@goatdb/goatdb";

// For production: load pre-built assets (generated by `deno task build`)
let encodedStaticAssets: JSONObject | undefined;
let buildInfo: BuildInfo | undefined;

try {
  const staticModule = await import("../build/staticAssets.json", { with: { type: "json" } });
  encodedStaticAssets = staticModule.default as JSONObject;
  const buildModule = await import("../build/buildInfo.json", { with: { type: "json" } });
  buildInfo = buildModule.default as BuildInfo;
} catch {
  // Not in production mode or build not run yet
}

export async function startServer(options: {
  port?: number;
  path?: string;
} = {}) {
  const { port = 8080, path: dataPath = ".smith/data" } = options;

  if (!encodedStaticAssets || !buildInfo) {
    console.error("No build artifacts found. Run `deno task build` first or use `deno task dev` for development.");
    Deno.exit(1);
  }

  const server = new Server({
    staticAssets: staticAssetsFromJS(encodedStaticAssets),
    path: path.join(Deno.cwd(), dataPath),
    buildInfo,
    port,
    domain: {
      resolveOrg: () => "smith",
      resolveDomain: () => "localhost",
    },
  });

  await server.start();
  console.log(`S.M.I.T.H running at http://localhost:${port}`);

  return server;
}

// CLI entry point
if (import.meta.main) {
  startServer();
}

export { GoatDB, Server };
export * from "./db/mod.ts";
